/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;
import java.sql.Connection;
import com.bd.Conexion;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;



public class Register extends javax.swing.JFrame {
    
   
    private boolean ValidarCorreo( String Correo){
        
            String CorreoRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            
            return Correo.matches(CorreoRegex);
        };
    
    private void Limpiar(){
        TxtUsuario.setText("");
        TxtCorreo.setText("");
        TxtPassword.setText("");
    };
        
  
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    
    
    public Register() {
        
        com.bd.Tablas.crear();
        
        initComponents();
        
       setTitle("Crear Cuenta");
       setSize(1000,700);
       setLocationRelativeTo(null);
       setResizable(false);
       setDefaultCloseOperation(EXIT_ON_CLOSE);
       setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JPasswordField();
        TxtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ButtonCreate = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 31, 41));
        jLabel6.setText("¿Ya tienes una cuenta?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, 40));

        jButton1.setBackground(new java.awt.Color(164, 68, 219));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicia sesión aquí.");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/angel.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(575, 666));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 666));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel2.setText("Crear cuenta");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel4.setText("Correo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel5.setText("Contraseña:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        TxtCorreo.setBorder(null);
        jPanel2.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 260, 40));

        TxtPassword.setBorder(null);
        jPanel2.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 260, 40));

        TxtUsuario.setBorder(null);
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 260, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 260, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 260, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 260, 20));

        ButtonCreate.setBackground(new java.awt.Color(0, 191, 255));
        ButtonCreate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonCreate.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCreate.setText("Crear Cuenta");
        ButtonCreate.setBorder(null);
        ButtonCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 150, 50));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateActionPerformed
        // TODO add your handling code here:
        String Usuario = TxtUsuario.getText().trim();
    String Correo = TxtCorreo.getText().trim();
    String Password = new String(TxtPassword.getPassword()).trim();
    
    // Validación 1: Campos vacíos específicos
    if(Usuario.isEmpty() && Correo.isEmpty() && Password.isEmpty()){
        JOptionPane.showMessageDialog(null,
            "Por favor, complete todos los campos para crear su cuenta",
            "Campos vacíos",
            JOptionPane.WARNING_MESSAGE);
        TxtUsuario.requestFocus();
        return;
    }
    
    if(Usuario.isEmpty()){
        JOptionPane.showMessageDialog(null,
            "Por favor, ingrese un nombre de usuario",
            "Usuario requerido",
            JOptionPane.WARNING_MESSAGE);
        TxtUsuario.requestFocus();
        return;
    }
    
    if(Correo.isEmpty()){
        JOptionPane.showMessageDialog(null,
            "Por favor, ingrese su correo electrónico",
            "Correo requerido",
            JOptionPane.WARNING_MESSAGE);
        TxtCorreo.requestFocus();
        return;
    }
    
    if(Password.isEmpty()){
        JOptionPane.showMessageDialog(null,
            "Por favor, ingrese una contraseña",
            "Contraseña requerida",
            JOptionPane.WARNING_MESSAGE);
        TxtPassword.requestFocus();
        return;
    }
    
    // Validación 2: Longitud del usuario
    if(Usuario.length() < 3){
        JOptionPane.showMessageDialog(null,
            "El nombre de usuario debe tener al menos 3 caracteres",
            "Usuario muy corto",
            JOptionPane.ERROR_MESSAGE);
        TxtUsuario.requestFocus();
        TxtUsuario.selectAll();
        return;
    }
    
    if(Usuario.length() > 50){
        JOptionPane.showMessageDialog(null,
            "El nombre de usuario no puede exceder 50 caracteres",
            "Usuario muy largo",
            JOptionPane.ERROR_MESSAGE);
        TxtUsuario.requestFocus();
        TxtUsuario.selectAll();
        return;
    }
    
    // Validación 3: Caracteres válidos en usuario
    if(!Usuario.matches("^[a-zA-Z0-9_.-]+$")){
        JOptionPane.showMessageDialog(null,
            "El usuario solo puede contener letras, números, guiones y puntos",
            "Caracteres no válidos",
            JOptionPane.ERROR_MESSAGE);
        TxtUsuario.requestFocus();
        TxtUsuario.selectAll();
        return;
    }
    
    // Validación 4: Formato de correo
    if(!ValidarCorreo(Correo)){
        JOptionPane.showMessageDialog(null,
            "El formato del correo electrónico no es válido.\nEjemplo: usuario@dominio.com",
            "Correo inválido",
            JOptionPane.ERROR_MESSAGE);
        TxtCorreo.requestFocus();
        TxtCorreo.selectAll();
        return;
    }
    
    // Validación 5: Longitud y seguridad de contraseña
    if(Password.length() < 6){
        JOptionPane.showMessageDialog(null,
            "La contraseña debe tener al menos 6 caracteres",
            "Contraseña muy corta",
            JOptionPane.ERROR_MESSAGE);
        TxtPassword.requestFocus();
        TxtPassword.selectAll();
        return;
    }
    
    if(Password.length() > 100){
        JOptionPane.showMessageDialog(null,
            "La contraseña no puede exceder 100 caracteres",
            "Contraseña muy larga",
            JOptionPane.ERROR_MESSAGE);
        TxtPassword.requestFocus();
        return;
    }
    
    // Validación 6: Verificar seguridad básica de contraseña
    if(Password.equals(Usuario) || Password.equals(Correo)){
        JOptionPane.showMessageDialog(null,
            "La contraseña no puede ser igual al usuario o correo",
            "Contraseña insegura",
            JOptionPane.ERROR_MESSAGE);
        TxtPassword.setText("");
        TxtPassword.requestFocus();
        return;
    }
    
    // Validación 7: Contraseña debe tener al menos una letra y un número
    boolean tieneLetra = Password.matches(".*[a-zA-Z].*");
    boolean tieneNumero = Password.matches(".*[0-9].*");
    
    if(!tieneLetra || !tieneNumero){
        JOptionPane.showMessageDialog(null,
            "La contraseña debe contener al menos:\n• Una letra\n• Un número",
            "Contraseña débil",
            JOptionPane.WARNING_MESSAGE);
        TxtPassword.requestFocus();
        return;
    }
    
    // Proceso de registro
    try(Connection db = Conexion.conectar()){
        
        if(db == null){
            JOptionPane.showMessageDialog(null,
                "No se pudo conectar a la base de datos.\nVerifique su conexión.",
                "Error de conexión",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Verificar si el usuario ya existe
        String verificarUsuario = "SELECT id FROM Usuarios WHERE Usuario = ?";
        PreparedStatement psVerifUsuario = db.prepareStatement(verificarUsuario);
        psVerifUsuario.setString(1, Usuario);
        
        if(psVerifUsuario.executeQuery().next()){
            JOptionPane.showMessageDialog(null,
                "Este nombre de usuario ya está en uso.\nPor favor, elija otro.",
                "Usuario no disponible",
                JOptionPane.WARNING_MESSAGE);
            TxtUsuario.requestFocus();
            TxtUsuario.selectAll();
            psVerifUsuario.close();
            return;
        }
        psVerifUsuario.close();
        
        // Verificar si el correo ya existe
        String verificarCorreo = "SELECT id FROM Usuarios WHERE Correo = ?";
        PreparedStatement psVerifCorreo = db.prepareStatement(verificarCorreo);
        psVerifCorreo.setString(1, Correo);
        
        if(psVerifCorreo.executeQuery().next()){
            JOptionPane.showMessageDialog(null,
                "Este correo electrónico ya está registrado.\n¿Desea iniciar sesión?",
                "Correo ya registrado",
                JOptionPane.WARNING_MESSAGE);
            TxtCorreo.requestFocus();
            TxtCorreo.selectAll();
            psVerifCorreo.close();
            return;
        }
        psVerifCorreo.close();
        
    
        String Consulta = "INSERT INTO Usuarios(Usuario, Correo, Contrasena) VALUES(?, ?, ?)";
        PreparedStatement ps = db.prepareStatement(Consulta);
        
        ps.setString(1, Usuario);
        ps.setString(2, Correo);
        ps.setString(3, Password);
        
        int filasAfectadas = ps.executeUpdate();
        ps.close();
        
        if(filasAfectadas > 0){
            Limpiar();
            
            int opcion = JOptionPane.showConfirmDialog(null,
                "¡Cuenta creada exitosamente!\n\n" +
                "Usuario: " + Usuario + "\n" +
                "Correo: " + Correo + "\n\n" +
                "¿Desea iniciar sesión ahora?",
                "Registro exitoso",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
            
            if(opcion == JOptionPane.YES_OPTION){
                Login IniciarSesion = new Login();
                IniciarSesion.setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null,
                "No se pudo crear la cuenta.\nIntente nuevamente.",
                "Error en registro",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch(java.sql.SQLIntegrityConstraintViolationException e){
        JOptionPane.showMessageDialog(null,
            "El usuario o correo ya están registrados en el sistema",
            "Datos duplicados",
            JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.WARNING, "Intento de registro duplicado", e);
        
    } catch(java.sql.SQLException e){
        JOptionPane.showMessageDialog(null,
            "Error en la base de datos: " + e.getMessage(),
            "Error SQL",
            JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error SQL en registro", e);
        
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,
            "Error inesperado al crear la cuenta.\nPor favor, intente nuevamente.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error en registro", e);
    }
  
  
    }//GEN-LAST:event_ButtonCreateActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Login IniciarSesion = new Login();

        IniciarSesion.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreate;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
