/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.Productos;

import com.bd.Conexion;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class NewServicioDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewServicioDialog.class.getName());

    private java.awt.Frame parentFrame;
    private boolean modoEditar = false;
    private int idServicioEditar = -1;
    
    
    public NewServicioDialog(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        this.parentFrame = parent;
        setUndecorated(true);
        initComponents();
        setSize(480, 480);
        setLocationRelativeTo(parent);
        setLocation(getX() + 60, getY() + 30);
        setResizable(false);
        
        cargarProductosDisponibles();
        configurarEventos();
       
        jLabel1.setText("Agregar Servicio");
        jButton1.setText("Agregar");
        
        configurarCheckboxes();
    }
    
    
     public NewServicioDialog(java.awt.Frame parent, boolean modal,
                            int idServicio, String nombreServicio, 
                            BigDecimal costoServicio, BigDecimal precioVenta,
                            Integer idProductoConsumo, double cantidadConsumo) {
        super(parent, modal);
       this.parentFrame = parent; 
        this.modoEditar = true;
        this.idServicioEditar = idServicio;
        
        setUndecorated(true);
        initComponents();
        setSize(480, 480);
        setLocationRelativeTo(parent);
        setLocation(getX() + 60, getY() + 30);
        setResizable(false);
        
        cargarProductosDisponibles();
        configurarEventos();
        configurarCheckboxes();
        
        jLabel1.setText("Editar Servicio");
        jButton1.setText("Actualizar");
        btnCerrar.setText("Cancelar");
        
        // Cargar datos existentes
        txtNombreS1.setText(nombreServicio); // Nombre del servicio
        txtNombreS2.setText(precioVenta.toString()); // Precio de venta
        
        if (idProductoConsumo != null && idProductoConsumo > 0) {
            Si.setSelected(true);
            No.setSelected(false);
            mostrarCamposConsumo(true);
            txtNombreS.setText(String.valueOf(cantidadConsumo)); // Cantidad que consume
            seleccionarProducto(idProductoConsumo);
        } else {
            No.setSelected(true);
            Si.setSelected(false);
            mostrarCamposConsumo(false);
        }
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreS1 = new javax.swing.JTextField();
        txtNombreS2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Si = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNombreS = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        No = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 191, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Servicios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nombre del servicio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Precio de venta:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 20));

        txtNombreS1.setEditable(true);
        txtNombreS1.setBackground(new java.awt.Color(245, 245, 245));
        txtNombreS1.setBorder(null);
        txtNombreS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreS1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 40));

        txtNombreS2.setEditable(true);
        txtNombreS2.setBackground(new java.awt.Color(245, 245, 245));
        txtNombreS2.setBorder(null);
        txtNombreS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreS2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 180, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Consume  algún ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Producto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Producto que consume:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 220, 20));

        Si.setText("Si");
        Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiActionPerformed(evt);
            }
        });
        jPanel1.add(Si, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<itemProducto>());
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 200, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Cantidad que consume:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 20));

        txtNombreS.setEditable(true);
        txtNombreS.setBackground(new java.awt.Color(245, 245, 245));
        txtNombreS.setBorder(null);
        txtNombreS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 190, 40));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cancelar");
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 90, 40));

        jButton1.setBackground(new java.awt.Color(0, 191, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 90, 40));

        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        jPanel1.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreS1ActionPerformed

    private void txtNombreS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreS2ActionPerformed

    private void SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiActionPerformed
        // TODO add your handling code here:
          if (Si.isSelected()) {
            No.setSelected(false);
            mostrarCamposConsumo(true);
        }
    }//GEN-LAST:event_SiActionPerformed

    private void txtNombreSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   if (!validarCampos()) {
        return;  // Si falla la validación, salimos del método
    }
    
  
    addServicios servicio = new addServicios();
    
    if (modoEditar) {
        servicio.actualizarServicio(
            idServicioEditar,
            txtNombreS1,
            new javax.swing.JTextField(),
            txtNombreS2,
            jComboBox1,
            txtNombreS,
            Si.isSelected()
        );
    } else {
        servicio.agregarServicio(
            txtNombreS1,
            new javax.swing.JTextField(),
            txtNombreS2,
            jComboBox1,
            txtNombreS,
            Si.isSelected()
        );
    }
    
    if (parentFrame instanceof GestionServicios) {
        ((GestionServicios) parentFrame).mostrarServicios();
    }
    
    dispose();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
        
        if (No.isSelected()) {
            Si.setSelected(false);
            mostrarCamposConsumo(false);
        }
    }//GEN-LAST:event_NoActionPerformed

   private void cargarProductosDisponibles() {
        try (Connection conexion = Conexion.conectar();
             PreparedStatement pst = conexion.prepareStatement(
                 "SELECT id, nombreProducto FROM Productos ORDER BY nombreProducto")) {
            
            ResultSet rs = pst.executeQuery();
            
            jComboBox1.removeAllItems();
            jComboBox1.addItem(new itemProducto(0, "-- No consume producto --"));
            
            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombreProducto");
                jComboBox1.addItem(new itemProducto(id, nombre));
            }
            
        } catch (Exception e) {
            System.out.println("Error cargando productos: " + e.getMessage());
        }
    }
    
    private void seleccionarProducto(int idProducto) {
        for (int i = 0; i < jComboBox1.getItemCount(); i++) {
            Object item = jComboBox1.getItemAt(i);
            if (item instanceof itemProducto) {
                itemProducto prod = (itemProducto) item;
                if (prod.getId() == idProducto) {
                    jComboBox1.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
    
    private void mostrarCamposConsumo(boolean mostrar) {
        jLabel7.setVisible(mostrar);     // "Producto que consume"
        jComboBox1.setVisible(mostrar);  // ComboBox productos
        jLabel4.setVisible(mostrar);     // "Cantidad que consume"
        txtNombreS.setVisible(mostrar);  // TextField cantidad
    }
    
    private void configurarCheckboxes() {
        No.setSelected(true);
        Si.setSelected(false);
        mostrarCamposConsumo(false); // Asegura que los campos estén ocultos al inicio
    }
    
    private void configurarEventos() {
        // Por ahora vacío, puedes agregar listeners aquí
    }
    
    private boolean validarCampos() {
        // Validar nombre del servicio
        if (txtNombreS1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del servicio");
            return false;
        }
        
        // Validar precio de venta
        if (txtNombreS2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el precio de venta");
            return false;
        }
        
        try {
            BigDecimal precio = new BigDecimal(txtNombreS2.getText().trim());
            if (precio.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a 0");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Precio de venta inválido");
            return false;
        }
        
        // Validar si consume producto
        if (Si.isSelected()) {
            // Validar que se seleccionó un producto válido
            itemProducto productoSeleccionado = (itemProducto) jComboBox1.getSelectedItem();
            if (productoSeleccionado == null || productoSeleccionado.getId() == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione un producto válido");
                return false;
            }
            
            if (txtNombreS.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad que consume");
                return false;
            }
            
            try {
                double cantidad = Double.parseDouble(txtNombreS.getText().trim());
                if (cantidad <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
                    return false;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cantidad inválida");
                return false;
            }
        }
        
        return true;
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewServicioDialog dialog = new NewServicioDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox No;
    private javax.swing.JCheckBox Si;
    private javax.swing.JButton btnCerrar;
    public javax.swing.JButton jButton1;
    private javax.swing.JComboBox<itemProducto> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNombreS;
    private javax.swing.JTextField txtNombreS1;
    private javax.swing.JTextField txtNombreS2;
    // End of variables declaration//GEN-END:variables
}
